version: '3.8'

services:
  node1:
    build: .
    container_name: chord-node1
    environment:
      - NODE_ID=1
      - NODE_ADDRESS=node1:8080
    networks:
      - chord-network
    ports:
      - "8081:8080"  # Expose node1 on localhost:8080

  node2:
    build: .
    container_name: chord-node2
    environment:
      - NODE_ID=2
      - NODE_ADDRESS=node2:8080
    networks:
      - chord-network
    ports:
      - "8082:8080"  # Expose node2 on localhost:8081

  node3:
    build: .
    container_name: chord-node3
    environment:
      - NODE_ID=Node3
      - NODE_ADDRESS=node3:8080
    networks:
      - chord-network
    ports:
      - "8083:8080"  # Expose node3 on localhost:8082

  node4:
    build: .
    container_name: chord-node4
    environment:
      - NODE_ID=Node4
      - NODE_ADDRESS=node4:8080
    networks:
      - chord-network
    ports:
      - "8084:8080"  # Expose node4 on localhost:8083

  node5:
    build: .
    container_name: chord-node5
    environment:
      - NODE_ID=Node5
      - NODE_ADDRESS=node5:8080
    networks:
      - chord-network
    ports:
      - "8085:8080"  # Expose node5 on localhost:8084

  node6:
    build: .
    container_name: chord-node6
    environment:
      - NODE_ID=Node6
      - NODE_ADDRESS=node6:8080
    networks:
      - chord-network
    ports:
      - "8086:8080"  # Expose node5 on localhost:8084

  node7:
    build: .
    container_name: chord-node7
    environment:
      - NODE_ID=Node7
      - NODE_ADDRESS=node7:8080
    networks:
      - chord-network
    ports:
      - "8087:8080"  # Expose node5 on localhost:8084

  node8:
    build: .
    container_name: chord-node8
    environment:
      - NODE_ID=Node8
      - NODE_ADDRESS=node8:8080
    networks:
      - chord-network
    ports:
      - "8088:8080"  # Expose node5 on localhost:8084

  node9:
    build: .
    container_name: chord-node9
    environment:
      - NODE_ID=Node9
      - NODE_ADDRESS=node9:8080
    networks:
      - chord-network
    ports:
      - "8089:8080"  # Expose node5 on localhost:8084

  node10:
    build: .
    container_name: chord-node10
    environment:
      - NODE_ID=Node10
      - NODE_ADDRESS=node10:8080
    networks:
      - chord-network
    ports:
      - "8090:8080"  # Expose node5 on localhost:8084

networks:
  chord-network:
    driver: bridge
